spring:
  rabbitmq:
    host: st.eomdev.com
    port: 5672
    username: stUser
    password: stPassword
    virtual-host: vhost02
server:
  port: 9999
custom:
  message: Hello, api ST! (devel branch)